# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  # Task Configurations Root Path
  TASK_ROOT: ".task"

  # Task Configuration Variables Path
  TASK_VARS: "{{.TASK_ROOT}}/vars"

  # Name of the Product
  PRODUCT_NAME: ""

  # Version of the Product
  PRODUCT_VERSION: ""

  # Commit Hash
  COMMIT_HASH:
    sh: git rev-parse HEAD

  # PRODUCT_NAME + PRODUCT_VERSION + COMMIT_HASH
  OCI_IMAGE:
    sh: echo "{{.PRODUCT_NAME}}:{{.PRODUCT_VERSION}}-{{.COMMIT_HASH}}"

  # Location
  AZ_LOCATION: ""

  # Resource Group
  AZ_RG: ""

  # Web App
  AZ_WEBAPP: ""

  # App Service Plan
  AZ_APPSERVICE_PLAN: ""

  # Key Vault
  AZ_KV: ""

  # Virtual Network
  AZ_VNET: ""

  # Subnet for Postgress
  AZ_SUBNET_PG: ""

  # Subnet for Web App
  AZ_SUBNET_WEBAPP: ""

  # Subnet for Private Endpoints
  AZ_SUBNET_PE: ""

  # Private DNS Link for Postgres
  AZ_PDNS_LINK_PG: ""

  # Private DNS Link for Key Vault
  AZ_PDNS_LINK_KV: ""

  # Private DNS Zone for Postgres
  AZ_PDNS_ZONE_PG: ""
  # AZ_PDNS_ZONE_PG: "privatelink.postgres.database.azure.com"

  # Private DNS Zone for Key Vault
  AZ_PDNS_ZONE_KV: "privatelink.vaultcore.azure.net"

  # Private Endpoint for Key Vault
  AZ_PE_KV: ""

  # Connection for Key Vault
  AZ_PE_CONNECTION_KV: ""

  # Private Endpoint DNS Zone Group
  AZ_PE_DNS_ZG_KV: ""

  # Azure Database for PostgreSQL flexible server instance
  AZ_PG_FLEX: ""

  # Posgtres DB user key
  AZ_PG_USR_KEY: ""

  # Posgtres DB password key
  AZ_PG_PWD_KEY: ""

  # Posgtres DB url key
  AZ_PG_DB_URL_KEY: ""

  # Container Registry
  AZ_ACR: ""

dotenv: [".env"]

tasks:
  default:
    desc: "Full deployment pipeline"
    cmds:
      - task: setup-env
      - task: setup-network
      - task: setup-pg
      - task: setup-kv
      - task: setup-acr
      - task: deploy-webapp-container
    silent: true

  clean-up:
    desc: Clean up all resources created for the Web App
    cmds:
      - rm -rf "{{.TASK_ROOT}}"

      # delete Resource Group idempotently
      - |
        az group delete --name "{{.AZ_RG}}" -y \
        || echo "Resource Group doesn't exist..."

      # delete Key Vault idempotently
      - |
        az keyvault purge --name "{{.AZ_KV}}" --location "{{.AZ_LOCATION}}" \
        || echo "Key Vault doesn't exist..."

  setup-env:
    desc: Setup environment
    cmds:
      # create task data folder
      - mkdir -p "{{.TASK_VARS}}"

      # create a Resource Group
      - az group create --name "{{.AZ_RG}}" --location "{{.AZ_LOCATION}}"

      # write Subscription ID to vars
      - az account show --query "id" --output tsv > "{{.TASK_VARS}}/AZ_SUBSCRIPTION_ID"

      # write User ID to vars
      - az ad signed-in-user show --query id -o tsv > "{{.TASK_VARS}}/AZ_USER_ID"

  setup-network:
    desc: Set Up a Virtual Network
    cmds:
      # create a Virtual Network
      - |
        az network vnet create \
          --name "{{.AZ_VNET}}" \
          --resource-group "{{.AZ_RG}}" \
          --location "{{.AZ_LOCATION}}" \
          --address-prefixes 10.2.0.0/16

      # create a Subnet for the Postgres Server
      - |
        az network vnet subnet create \
          --resource-group "{{.AZ_RG}}" \
          --vnet-name "{{.AZ_VNET}}" \
          --name "{{.AZ_SUBNET_PG}}" \
          --address-prefixes 10.2.2.0/24 \
          --delegations Microsoft.DBforPostgreSQL/flexibleServers \
          --private-endpoint-network-policies Enabled

      # create a Subnet for the Private Endpoints
      - |
        az network vnet subnet create \
            --resource-group "{{.AZ_RG}}" \
            --vnet-name "{{.AZ_VNET}}" \
            --name "{{.AZ_SUBNET_PE}}" \
            --address-prefixes 10.2.3.0/27

      # create a Subnet for the Web App
      - |
        az network vnet subnet create \
            --resource-group "{{.AZ_RG}}" \
            --vnet-name "{{.AZ_VNET}}" \
            --name "{{.AZ_SUBNET_WEBAPP}}" \
            --address-prefixes 10.2.4.0/27 \
            --delegations Microsoft.Web/serverFarms

  setup-pg:
    desc: Set Up a Postgres Flexible Server
    cmds:
      # create a Private DNS Zone for Postgres Server
      - |
        az network private-dns zone create \
            --name "{{.AZ_PDNS_ZONE_PG}}" \
            --resource-group "{{.AZ_RG}}"

      # link the Postgres Private DNS Zone to the Virtual Network
      - |
        az network private-dns link vnet create \
            --name "{{.AZ_PDNS_LINK_PG}}" \
            --resource-group "{{.AZ_RG}}" \
            --zone-name "{{.AZ_PDNS_ZONE_PG}}" \
            --virtual-network "{{.AZ_VNET}}" \
            --registration-enabled false

      # create an Azure Database for PostgreSQL flexible server instance
      - |
        az postgres flexible-server create \
            --subscription "$(cat {{.TASK_VARS}}/AZ_SUBSCRIPTION_ID)" \
            --resource-group "{{.AZ_RG}}" \
            --name "{{.AZ_PG_FLEX}}" \
            --location "{{.AZ_LOCATION}}" \
            --version 18 \
            --zone 1 \
            --password-auth enabled \
            --admin-user "{{.AZ_PG_USR_VAL}}" \
            --admin-password "{{.AZ_PG_PWD_VAL}}" \
            --tier burstable \
            --sku-name Standard_B1ms \
            --storage-type Premium_LRS \
            --storage-size 32 \
            --storage-auto-grow disabled \
            --backup-retention 7 \
            --zonal-resiliency disabled \
            --vnet "{{.AZ_VNET}}" \
            --subnet "{{.AZ_SUBNET_PG}}" \
            --private-dns-zone "{{.AZ_PDNS_ZONE_PG}}"

  setup-kv:
    desc: Set Up a Key Vault
    cmds:
      # create a Key Vault for the Web App
      - |
        az keyvault create \
            --name "{{.AZ_KV}}" \
            --resource-group "{{.AZ_RG}}" \
            --public-network-access Enabled \
            --default-action deny

      # write Keyvault ID to vars
      - az keyvault show --name "{{.AZ_KV}}" --query id -o tsv > "{{.TASK_VARS}}/AZ_KV_ID"

      # add a Network Rule to allow local access to the Key Vault
      - |
        az keyvault network-rule add \
          --name "{{.AZ_KV}}" \
          --resource-group "{{.AZ_RG}}" \
          --ip-address "$(curl ifconfig.me)"

      # assign Key Vault Secrets Officer role to the current user to allow managing secrets
      - |
        az role assignment create \
            --assignee "$(cat {{.TASK_VARS}}/AZ_USER_ID)" \
            --role "Key Vault Secrets Officer" \
            --scope "$(cat {{.TASK_VARS}}/AZ_KV_ID)"

      # set Postgres username to the Key Vault
      - |
        for i in {1..6}; do
          if az keyvault secret set \
            --vault-name "{{.AZ_KV}}" \
            --name "{{.AZ_PG_USR_KEY}}" \
            --value "{{.AZ_PG_USR_VAL}}";
          then
            echo "Secret set successfully!"
            break
          else
            echo "Failed to set secret. Retrying in 10s... ($i/6)"
            sleep 10
          fi
        done

      # set Postgres password to the Key Vault
      - |
        az keyvault secret set \
            --vault-name "{{.AZ_KV}}" \
            --name "{{.AZ_PG_PWD_KEY}}" \
            --value "{{.AZ_PG_PWD_VAL}}"

      # Postgres DB url
      - echo "jdbc:postgresql://{{.AZ_FQDN_PG}}:5432/postgres?sslmode=require" > {{.TASK_VARS}}/AZ_PG_DB_URL_VAL

      # set Postgres DB url to the Key Vault
      - |
        az keyvault secret set \
            --vault-name "{{.AZ_KV}}" \
            --name "{{.AZ_PG_DB_URL_KEY}}" \
            --value "$(cat {{.TASK_VARS}}/AZ_PG_DB_URL_VAL)"

      # disable public access
      - |
        az keyvault update \
            --name "{{.AZ_KV}}" \
            --resource-group "{{.AZ_RG}}" \
            --public-network-access Disabled

      # delete the Network Rule for the Key Vault
      - |
        az keyvault network-rule remove \
            --name "{{.AZ_KV}}" \
            --resource-group "{{.AZ_RG}}" \
            --ip-address $(curl ifconfig.me)

      # create a Private DNS Zone for Key Vault
      - |
        az network private-dns zone create \
            --name "{{.AZ_PDNS_ZONE_KV}}" \
            --resource-group "{{.AZ_RG}}"

      # write Key Vault Private DNS Zone ID to vars
      - |
        az network private-dns zone show \
            --name "{{.AZ_PDNS_ZONE_KV}}" \
            --resource-group "{{ .AZ_RG}}" \
            --query id -o tsv > "{{ .TASK_VARS}}/AZ_PDNS_ZONE_KV_ID"

      # link the Key Vault Private DNS Zone to the Virtual Network
      - |
        az network private-dns link vnet create \
            --name "{{ .AZ_PDNS_LINK_KV}}" \
            --resource-group "{{ .AZ_RG}}" \
            --zone-name "{{ .AZ_PDNS_ZONE_KV}}" \
            --virtual-network "{{ .AZ_VNET}}" \
            --registration-enabled false

      # create a Private Endpoint for accessing the Key Vault
      - |
        az network private-endpoint create \
            --name "{{ .AZ_PE_KV}}" \
            --vnet-name "{{ .AZ_VNET}}" \
            --subnet "{{ .AZ_SUBNET_PE}}" \
            --private-connection-resource-id "$(cat {{.TASK_VARS}}/AZ_KV_ID)" \
            --group-id vault \
            --connection-name "{{.AZ_PE_CONNECTION_KV}}" \
            --resource-group "{{.AZ_RG}}"

      # associate the Private Endpoint with the Private DNS Zone
      - |
        az network private-endpoint dns-zone-group create \
            --resource-group "{{.AZ_RG}}" \
            --endpoint-name "{{.AZ_PE_KV}}" \
            --name "{{.AZ_PE_DNS_ZG_KV}}" \
            --private-dns-zone "$(cat {{.TASK_VARS}}/AZ_PDNS_ZONE_KV_ID)" \
            --zone-name "{{.AZ_PDNS_ZONE_KV}}"

    vars:
      AZ_FQDN_PG:
        # Postgres Server Fully Qualified Domain Name
        sh: |
          az postgres flexible-server show \
            --name "{{.AZ_PG_FLEX}}" \
            --resource-group "{{.AZ_RG}}" \
            --output tsv \
            --query fullyQualifiedDomainName

  setup-acr:
    desc: Set Up a Azure Container Registry
    cmds:
      # create a Azure Container Registry
      - |
        az acr create \
          --name "{{.AZ_ACR}}" \
          --resource-group "{{.AZ_RG}}" \
          --role-assignment-mode 'rbac-abac' \
          --dnl-scope 'SubscriptionReuse' \
          --sku 'Basic'

      # write the Azure Container Registry ID to vars
      - |
        az acr show \
          --name "{{.AZ_ACR}}" \
          --query id -o tsv > "{{.TASK_VARS}}/AZ_ACR_ID"

      # assign the 'Container Registry Repository Writer' role to the current user to allow pushing images
      - |
        az role assignment create \
          --assignee "$(cat {{.TASK_VARS}}/AZ_USER_ID)" \
          --role 'Container Registry Repository Writer' \
          --scope "$(cat {{.TASK_VARS}}/AZ_ACR_ID)"

      # login to the Azure Container Registry
      - az acr login --name "{{.AZ_ACR}}"

      # write the Azure Container Registry path to vars
      - |
        az acr show \
          --name "{{.AZ_ACR}}" \
          --resource-group "{{.AZ_RG}}" \
          --output tsv \
          --query loginServer > "{{.TASK_VARS}}/AZ_ACR_REGISTRY"

      # write the Azure Container Registry path to vars
      - |
        echo "$(cat {{.TASK_VARS}}/AZ_ACR_REGISTRY)/flight-service:0.8.1-{{.COMMIT_HASH}}" \
          > "{{.TASK_VARS}}/OCI_IMAGE_NAME"

      # build a Docker Image
      - docker build -t "$(cat {{.TASK_VARS}}/OCI_IMAGE_NAME)" .

      # push the Docker Image to the registry
      - docker push "$(cat {{.TASK_VARS}}/OCI_IMAGE_NAME)"

  deploy-webapp-container:
    desc: Deploy the oci container to the Azure App Service
    cmds:
      # create an Azure App Service Plan
      - |
        az appservice plan create \
          --name "{{.AZ_APPSERVICE_PLAN}}" \
          --subscription "$(cat {{.TASK_VARS}}/AZ_SUBSCRIPTION_ID)" \
          --resource-group "{{.AZ_RG}}" \
          --location "{{.AZ_LOCATION}}" \
          --is-linux \
          --sku 'B1'

      # create an Web App
      - |
        az webapp create \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}" \
          --plan "{{.AZ_APPSERVICE_PLAN}}" \
          --container-image-name "$(cat {{.TASK_VARS}}/OCI_IMAGE_NAME)"

      # set environment variables for the Web App
      - |
        az webapp config appsettings set \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}" \
          --settings WEBSITES_PORT='8001' \
              ACTIVE_PROFILE='azure' \
              AZ_KV="{{.AZ_KV}}" \
              AZ_KV_URI="{{.AZ_KV_URI}}" \
              AZ_PG_USR="$(printf '${%s}' {{.AZ_PG_USR_KEY}})" \
              AZ_PG_PWD="$(printf '${%s}' {{.AZ_PG_PWD_KEY}})" \
              AZ_PG_DB_URL="$(printf '${%s}' {{.AZ_PG_DB_URL_KEY}})"

      # integrate the Web App into the VNET
      - |
        az webapp vnet-integration add \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}" \
          --vnet "{{.AZ_VNET}}" \
          --subnet "{{.AZ_SUBNET_WEBAPP}}"

      # configure logging to filesystem
      - |
        az webapp log config \
          --docker-container-logging filesystem \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}" \
          --level information

      # enable system-assigned identity for the Web App
      - |
        az webapp identity assign \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}"

      # configure the Web App to use the managed identity to pull the OCI image
      - |
        az webapp config set \
          --name "{{.AZ_WEBAPP}}" \
          --resource-group "{{.AZ_RG}}" \
          --generic-configurations '{"acrUseManagedIdentityCreds": true}'

      # write Web App System Identity ID to vars
      - |
        az webapp identity show \
          --resource-group "{{.AZ_RG}}" \
          --name "{{.AZ_WEBAPP}}" \
          --query principalId -o tsv > "{{.TASK_VARS}}/AZ_WEBAPP_SYSTEM_IDENTITY_ID"

      - |
        az role assignment create \
          --assignee "$(cat {{.TASK_VARS}}/AZ_WEBAPP_SYSTEM_IDENTITY_ID)" \
          --role 'Container Registry Repository Reader' \
          --scope "$(cat {{.TASK_VARS}}/AZ_ACR_ID)"

      # assign the Key Vault Secrets User role to the system-assigned identity
      - |
        az role assignment create \
          --role 'Key Vault Secrets User' \
          --assignee "$(cat {{.TASK_VARS}}/AZ_WEBAPP_SYSTEM_IDENTITY_ID)" \
          --scope "$(cat {{.TASK_VARS}}/AZ_KV_ID)"

      # restart the Web App
      - az webapp restart --name "{{.AZ_WEBAPP}}" --resource-group "{{.AZ_RG}}"

      # stream the Web App logs
      - az webapp log tail --name "{{.AZ_WEBAPP}}" --resource-group "{{.AZ_RG}}"
    vars:
      AZ_KV_URI:
        sh: |
          az keyvault show \
            --name "{{.AZ_KV}}" \
            --resource-group "{{.AZ_RG}}" \
            --output tsv \
            --query "properties.vaultUri"

  deploy-webapp-jar:
    desc: Deploy the app jar artifact to the Azure App Service
    cmds:
      - |
        gradle clean azureWebAppDeploy \
            -Paz-subscription="$(cat {{.TASK_VARS}}/AZ_SUBSCRIPTION_ID)" \
            -Paz-region="{{.AZ_LOCATION}}" \
            -Paz-rg="{{.AZ_RG}}" \
            -Paz-webapp="{{.AZ_WEBAPP}}" \
            -Paz-kv="{{.AZ_KV}}" \
            -Paz-kv-uri="{{.AZ_KV_URI}}" \
            -Paz-pg-usr="$(printf '${%s}' {{.AZ_PG_USR_KEY}})" \
            -Paz-pg-pwd="$(printf '${%s}' {{.AZ_PG_PWD_KEY}})" \
            -Paz-pg-db-url="$(printf '${%s}' {{.AZ_PG_DB_URL_KEY}})"

      # integrate the Web App into the VNET
      - |
        az webapp vnet-integration add \
            --name "{{.AZ_WEBAPP}}" \
            --resource-group "{{.AZ_RG}}" \
            --vnet "{{.AZ_VNET}}" \
            --subnet "{{.AZ_SUBNET_WEBAPP}}"

      # configure logging to filesystem
      - |
        az webapp log config \
            --application-logging filesystem \
            --name "{{.AZ_WEBAPP}}" \
            --resource-group "{{.AZ_RG}}" \
            --level information

      # enable system-assigned identity for the Web App
      - |
        az webapp identity assign \
            --name "{{.AZ_WEBAPP}}" \
            --resource-group "{{.AZ_RG}}"

      # write Web App System Identity ID to vars
      - az webapp identity show \
        --resource-group "{{.AZ_RG}}" \
        --name "{{.AZ_WEBAPP}}" \
        --query principalId -o tsv > "{{.TASK_VARS}}/AZ_WEBAPP_SYSTEM_IDENTITY_ID"

      # assign the Key Vault Secrets User role to the system-assigned identity
      - |
        az role assignment create \
            --role "Key Vault Secrets User" \
            --assignee "$(cat {{.TASK_VARS}}/AZ_WEBAPP_SYSTEM_IDENTITY_ID)" \
            --scope "$(cat {{.TASK_VARS}}/AZ_KV_ID)"

      # restart the Web App
      - az webapp restart --name "{{.AZ_WEBAPP}}" --resource-group "{{.AZ_RG}}"

      # stream the Web App logs
      - az webapp log tail --name "{{.AZ_WEBAPP}}" --resource-group "{{.AZ_RG}}"
    vars:
      AZ_KV_URI:
        sh: |
          az keyvault show \
            --name "{{.AZ_KV}}" \
            --resource-group "{{.AZ_RG}}" \
            --output tsv \
            --query "properties.vaultUri"
