info:
  system: Flight Service
  environment: Local

spring:
  application:
    name: flight-service
  profiles:
    active: ${ACTIVE_PROFILE:local}
  config:
    import: ""
  cloud:
    config:
      enabled: false
      uri: http://localhost:8005
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
    hikari:
      maximum-pool-size: 5
      connection-timeout: 2000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  #  sql:
  #    init:
  #      mode: always
  lifecycle:
    timeout-per-shutdown-phase: 15s
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/travel-booking-system}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, metrics, prometheus, liquibase, info, heapdump
  endpoint:
    health:
      show-components: always
      show-details: always
      probes:
        enabled: true
    heapdump:
      access: unrestricted
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

server:
  port: 8001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      min-spare: 5
      max: 50
  shutdown: graceful

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"
